# Generated by Django 3.0.1 on 2021-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_image', '0002_auto_20210303_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('easy_img', models.ImageField(upload_to='easy/')),
                ('hard_img', models.ImageField(upload_to='hard/')),
                ('retro_img', models.ImageField(default='SOME_STRING', upload_to='retro/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
